name = "lpc55xpresso"
target = "thumbv8m.main-none-eabihf"
board = "lpcxpresso55s69"
chip = "../../chips/lpc55"
stacksize = 1024
secure-separation = true

[kernel]
name = "lpc55xpresso"
requires = {flash = 32768, ram = 4096}
features = ["itm"]

[outputs.bootloader_sram]
address = 0x14000000
size = 0x8000

[outputs.bootloader_flash]
address = 0x00000000
size = 0x7000

[outputs.bootloader_ram]
address = 0x20000000
size = 0x4000

# We reserve the last sector (0x8000) for flash testing
[outputs.flash]
address = 0x00008000
size = 0x88000
read = true
execute = true

[outputs.ram]
address = 0x20004000
size = 0x18000
read = true
write = true
execute = true

[signing.combined]
method = "ecc"
priv-key = "../../support/fake_certs/p256-private-key.der"

[signing.bootloader]
method = "rsa"
priv-key = "../../support/fake_certs/fake_private_key.pem"
root-cert = "../../support/fake_certs/fake_certificate.der.crt"

[bootloader]
name = "stage0"
# Currently we have the first 0x8000 of flash and first 0x4000 of RAM
# dedicated for the stage0 bootloader and the rest for Hubris. Once we have
# multiple images this will need to be adjusted
imagea-flash-start = 0x8000
imagea-flash-size = 0x88000
imagea-ram-start = 0x20004000
imagea-ram-size = 0x18000
features = ["tz_support"]

[tasks.jefe]
name = "task-jefe"
priority = 0
max-sizes = {flash = 8192, ram = 2048}
start = true
features = ["itm"]
stacksize = 1536

[tasks.hiffy]
name = "task-hiffy"
priority = 5
features = ["lpc55"]
max-sizes = {flash = 32768, ram = 16384 }
stacksize = 2048
start = true

[tasks.idle]
name = "task-idle"
priority = 7
max-sizes = {flash = 256, ram = 256}
stacksize = 256
start = true

[tasks.lpc55_uartecho]
name = "task-lpc55-uartecho"
priority = 4
# inflated for ringbuf for debugging & demo
max-sizes = {flash = 65536, ram = 16384}
stacksize = 8192
start = true
uses = ["iocon", "gpio", "flexcomm0", "syscon"]
